name: ppi_tiongkok
description: PPI Tiongkok Mobile Application

dependencies:
  flutter:
    sdk: flutter

  fluro: ^1.3.5
  flutter_sparkline: ^0.1.0
  flutter_staggered_grid_view: ^0.2.3
  transparent_image: ^0.1.0
  flutter_webview_plugin: ^0.2.0
  url_launcher: ^4.0.1
  flutter_pdf_viewer: ^0.2.2
  path_provider: ^0.5.0+1
  mailer: ^2.0.2
  flutter_spinkit: ^3.1.0
  flutter_html: ^0.8.1
  firebase_auth: ^0.8.4+2
  firebase_core: ^0.3.4
  firebase_database: ^2.0.2
  firebase_storage: ^2.1.0+1
  cloud_firestore: ^0.9.13
  cached_network_image: ^0.7.0
  shared_preferences: ^0.4.3
  fluttertoast: ^3.0.3
  image_picker: ^0.5.2

dependency_overrides:
  http: 0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.6.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/logo.png"
  image_path_android: "assets/img/logo.png"
  image_path_ios: "assets/img/logo.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - res/logo.jpg
    - res/djauharioratmangun.jpg
    - res/fadlanmuzakki.png
    - res/bendera.jpg
    - assets/img/timur.png
    - assets/img/utara.png
    - assets/img/selatan.png
    - assets/img/no_image.jpg
    - assets/img/krjogja.png
    - assets/img/myhomieclub.png
    - assets/img/rilisid.png
    - assets/img/simposium.png
    - assets/pdf/ADART.pdf
    - assets/pdf/STRUKTUR.pdf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/
  
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
